config/routes.rb
Quinielas::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :destroy, :create]
  resources :tournaments  
  root :to => 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup', to: 'users#new'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :description, :name
  belongs_to :user
  validates :name, presence: true, length: { maximum: 50}, uniqueness: { case_sensitive: false }
  validates :description, presence:true, length: {maximum: 100 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :tournaments
  before_save :create_remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format:{ with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  before_save {
    |user| user.email = email.downcase
  }
  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/pwd combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_filter :signed_in_user
  
  def new
    @tournament = Tournament.new
  end

  def edit
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  def index
  end

  def create
    @tournament = current_user.tournaments.build(params[:tournament])
    if @tournament.save
      flash[:success] = "Tournament Created"
      redirect_to @tournament
    else
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index]
  before_filter :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
  end

  def edit
    
  end

  def update
    
    if @user.update_attributes(params[:user])
      flash[:success] = "success"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] ="Welcome #{@user.name}"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  private
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
    base_title = "Quinielas "
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end
  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to (session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in"
    end
  end
  private
    def clear_return_to
      session.delete(:return_to)
    end
    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "sample app", "#", id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home",  root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if signed_in? %>
              <li><%= link_to "Users", '#' %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Tournaments<b class="caret"></b>
                </a>
                <ul class="dropdown-menu" >
                <li><%= link_to "New Tournament", new_tournament_path %></li>
                </ul>
              </li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              <li><%= link_to "Profile", current_user %></li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))  %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %> </div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |e| %>
        <li>* <%= e %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/tournaments/edit.html.erb
<h1>Tournaments#edit</h1>
<p>Find me in app/views/tournaments/edit.html.erb</p>

app/views/tournaments/new.html.erb
<% provide(:title, 'New Tournament') %>
<h1>New Tournament</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@tournament) do |f| %>
      <%= render 'shared/error_messages', object: @tournament %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :description %>
      <%= f.text_field :description %>
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tournaments/show.html.erb
<h1>Tournaments#show</h1>
<p>Find me in app/views/tournaments/show.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title,'Edit User') %>

<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <p> <%= link_to "change", 'http://gravatar.com/emails' %>
  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>    
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside span="4">
    <section>
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>   
    <section>
  </aside>
</div>